// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetApiSampleSampleIndexGetData, GetApiSampleSampleIndexGetResponses, GetApiSampleSampleIndexGetErrors, GetApiRolloutRolloutIdGetData, GetApiRolloutRolloutIdGetResponses, GetApiRolloutRolloutIdGetErrors, RootGetData, RootGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get
 */
export const getApiSampleSampleIndexGet = <ThrowOnError extends boolean = false>(options: Options<GetApiSampleSampleIndexGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiSampleSampleIndexGetResponses, GetApiSampleSampleIndexGetErrors, ThrowOnError>({
        url: '/api/sample/{sample_index}',
        ...options
    });
};

/**
 * Get
 */
export const getApiRolloutRolloutIdGet = <ThrowOnError extends boolean = false>(options: Options<GetApiRolloutRolloutIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetApiRolloutRolloutIdGetResponses, GetApiRolloutRolloutIdGetErrors, ThrowOnError>({
        url: '/api/rollout/{rollout_id}',
        ...options
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<RootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};