// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * RolloutGetResponse
 */
export type RolloutGetResponse = {
    [key: string]: unknown;
};

/**
 * SampleGetResponse
 */
export type SampleGetResponse = {
    [key: string]: unknown;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetApiSampleSampleIndexGetData = {
    body?: never;
    path: {
        /**
         * Sample Index
         */
        sample_index: number;
    };
    query?: never;
    url: '/api/sample/{sample_index}';
};

export type GetApiSampleSampleIndexGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiSampleSampleIndexGetError = GetApiSampleSampleIndexGetErrors[keyof GetApiSampleSampleIndexGetErrors];

export type GetApiSampleSampleIndexGetResponses = {
    /**
     * Successful Response
     */
    200: SampleGetResponse;
};

export type GetApiSampleSampleIndexGetResponse = GetApiSampleSampleIndexGetResponses[keyof GetApiSampleSampleIndexGetResponses];

export type GetApiRolloutRolloutIdGetData = {
    body?: never;
    path: {
        /**
         * Rollout Id
         */
        rollout_id: number;
    };
    query?: never;
    url: '/api/rollout/{rollout_id}';
};

export type GetApiRolloutRolloutIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiRolloutRolloutIdGetError = GetApiRolloutRolloutIdGetErrors[keyof GetApiRolloutRolloutIdGetErrors];

export type GetApiRolloutRolloutIdGetResponses = {
    /**
     * Successful Response
     */
    200: RolloutGetResponse;
};

export type GetApiRolloutRolloutIdGetResponse = GetApiRolloutRolloutIdGetResponses[keyof GetApiRolloutRolloutIdGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};