// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MetadataGetTokenizerResponse
 */
export type MetadataGetTokenizerResponse = {
    /**
     * Id To Str
     */
    id_to_str: {
        [key: string]: string;
    };
};

/**
 * RolloutGetResponse
 */
export type RolloutGetResponse = {
    /**
     * Table Rows
     */
    table_rows: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * SampleGetResponse
 */
export type SampleGetResponse = {
    /**
     * Rollout Id
     */
    rollout_id: number;
    /**
     * Sample Index
     */
    sample_index: number;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Tokens
     */
    tokens: Array<number>;
    /**
     * Response
     */
    response: string;
    /**
     * Response Length
     */
    response_length: number;
    /**
     * Reward Value
     */
    reward_value: number;
    /**
     * Status
     */
    status: string;
    /**
     * Loss Masks
     */
    loss_masks: Array<number>;
    /**
     * Ref Log Probs
     */
    ref_log_probs: Array<number>;
    /**
     * Log Probs
     */
    log_probs: Array<number>;
    /**
     * Ref Probs
     */
    ref_probs: Array<number>;
    /**
     * Probs
     */
    probs: Array<number>;
    /**
     * Advantages
     */
    advantages: Array<number>;
    /**
     * Returns
     */
    returns: Array<number>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetTokenizerApiMetadataTokenizerGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Run Id
         */
        run_id: string;
    };
    url: '/api/metadata/tokenizer';
};

export type GetTokenizerApiMetadataTokenizerGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTokenizerApiMetadataTokenizerGetError = GetTokenizerApiMetadataTokenizerGetErrors[keyof GetTokenizerApiMetadataTokenizerGetErrors];

export type GetTokenizerApiMetadataTokenizerGetResponses = {
    /**
     * Successful Response
     */
    200: MetadataGetTokenizerResponse;
};

export type GetTokenizerApiMetadataTokenizerGetResponse = GetTokenizerApiMetadataTokenizerGetResponses[keyof GetTokenizerApiMetadataTokenizerGetResponses];

export type GetApiSampleSampleIndexGetData = {
    body?: never;
    path: {
        /**
         * Sample Index
         */
        sample_index: number;
    };
    query: {
        /**
         * Run Id
         */
        run_id: string;
    };
    url: '/api/sample/{sample_index}';
};

export type GetApiSampleSampleIndexGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiSampleSampleIndexGetError = GetApiSampleSampleIndexGetErrors[keyof GetApiSampleSampleIndexGetErrors];

export type GetApiSampleSampleIndexGetResponses = {
    /**
     * Successful Response
     */
    200: SampleGetResponse;
};

export type GetApiSampleSampleIndexGetResponse = GetApiSampleSampleIndexGetResponses[keyof GetApiSampleSampleIndexGetResponses];

export type GetApiRolloutRolloutIdGetData = {
    body?: never;
    path: {
        /**
         * Rollout Id
         */
        rollout_id: number;
    };
    query: {
        /**
         * Run Id
         */
        run_id: string;
    };
    url: '/api/rollout/{rollout_id}';
};

export type GetApiRolloutRolloutIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiRolloutRolloutIdGetError = GetApiRolloutRolloutIdGetErrors[keyof GetApiRolloutRolloutIdGetErrors];

export type GetApiRolloutRolloutIdGetResponses = {
    /**
     * Successful Response
     */
    200: RolloutGetResponse;
};

export type GetApiRolloutRolloutIdGetResponse = GetApiRolloutRolloutIdGetResponses[keyof GetApiRolloutRolloutIdGetResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};